### ISSUE TITLE
don't open wrong "div"

### ISSUE THREAD

**Issue by MuslimbekSalimov** [RAVSHANOV-MAMUR/imtihon#1]
https://github.com/RAVSHANOV-MAMUR/imtihon/blob/430817c879407262b70f37ef0d32f030e366299f/index.html#L41C1-L41C1

diving notog'ri ochilgan va ishlatilmagan

**Comment by RAVSHANOV-MAMUR** [comment]
close

**Comment by MuslimbekSalimov** [comment]
cunmadm

вт, 31 окт. 2023 г. в 17:46, RAVSHANOV-MAMUR ***@***.***>:

**Comment by MuslimbekSalimov** [comment]
Qalisan bratish

пт, 3 нояб. 2023 г. в 19:25, Muslimbek Salimov <
***@***.***>:
